name: preview

on:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Publish preview
        run: expo publish --release-channel pr-${{ github.event.number }}
      
      - name: 💬 Comment preview
        uses: expo/expo-github-action/preview-comment@v7
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          channel: pr-${{ github.event.number }}

